### ISSUE TITLE
Create page to send comments related to events

### ISSUE THREAD

**Issue by kwhitehall** [CFLBajans/cfbajans-website-legacy#14]
Specifically, the Taste of Barbados event. 
Persons should be able to anonymously send feedback here.

**Comment by millserd** [comment]
I will have to think more about the implementation of this. I would like to somehow tie this into the matching facebook event page comments.

**Comment by kwhitehall** [comment]
Was thinking to make the event a link on the events page calendar. When that link is clicked, it'll render a simple form to send an email to the core info address / event organizers addresses with the comments. Thoughts?

**Comment by millserd** [comment]
Hmm..So this is more for private comments. Ok. This is doable. What about the Facebook event comments though...Not the same thing?

**Comment by kwhitehall** [comment]
The FB comments associated with events should also be implemented. I think on every linking to the other may suffice. The event coordinators can check both sources for the feedback. Thoughts?

**Comment by kwhitehall** [comment]
[EDIT] FB comments on the FB events page implemented thru FB.

**Comment by millserd** [comment]
Ok. I will look and see how this can be done. I plan to work on this very soon.

**Comment by kwhitehall** [comment]
Hi @millserd. Drafted the comments with Balsamiq for a better visual. Thoughts?
[feedbackv1.pdf](https://github.com/CFLBajans/cfbajans-website-legacy/files/936030/feedbackv1.pdf)
[EDIT] PS: Can't update the Balsamiq file here. Let me know if you want it emailed to edit.

**Comment by millserd** [comment]
wow. im really impressed. The page layout for the event looks fantastic. I say we go with it.
The calendar page works but could be improved some. It would be nice if somehow the entire year could be condensed onto the page with minimal scrolling.

**Comment by millserd** [comment]
Also, what do you think about embedding a google calendar instead? Easier to maintain, though not the prettiest thing. Here is an example: https://pdxblues.com/events/
It is responsive though. (scales and works on phones)

**Comment by kwhitehall** [comment]
Love the Google calendar idea! +1

**Comment by kwhitehall** [comment]
So. The questions is, to implement it now or save it for new site. My position is take the path of least resistance here. If you can easily implement it now in this PR, go for it, else we should open another issue re adding google calendar and tag it as upgrade (i.e for the new site).

**Comment by kwhitehall** [comment]
Addressed in PR #21 and #29.
