### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cfbajans-website-legacy#22]
Rearrange the home page to remove the outdated text and move the events up.

**Comment by kwhitehall** [comment]
I think ordering as "the mission statement", "upcoming events", and then President's msg. Thoughts?

**Comment by kwhitehall** [comment]
Addressed in PR #25. @KillahB please have a look at the website and report here if the reorganization sufficiently addresses your concerns. Thanks!

**Comment by KillahB** [comment]
@kwhitehall 
Looks good, but the President's message can also be removed and archived.

**Comment by KillahB** [comment]
Looks good.
