### ISSUE TITLE
Create archive page for events

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cfbajans-website-legacy#35]
Page can be either on Facebook for image archives or a file location where we can host pictures and videos of past events.

**Comment by kwhitehall** [comment]
This is in the layout design as the gallery pages, but they are yet to be designed. We may want to consider gallery styles and consider  how easy the page(s) will be to update (based on the design), when pics come in after the event.

**Comment by kwhitehall** [comment]
@KillahB please see if the implementation on the [cflbajans repo](https://github.com/CFLBajans/cflbajans) addresses this. 
EDIT:
Open any other related issues against that repo please.

**Comment by KillahB** [comment]
@kwhitehall Addressed on new site.
