### ISSUE TITLE
Idea for Traffic Generation - Recipe Page

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cfbajans-website-legacy#36]
For consideration, please create a 'Recipe' page on the new website where we can upload Bajan recipes and recipes from different featured members

**Comment by kwhitehall** [comment]
Ack'ed @KillahB. Will update the layout to include.

**Comment by kwhitehall** [comment]
Addressed on [cflbajans repo](https://github.com/CFLBajans/cflbajans)
