### ISSUE TITLE
Idea for Traffic Generation - Featured Members Page

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cfbajans-website-legacy#37]
Please create a page where we can feature different members each month or so, to generate traffic and interest, and get to know some of the CFL Bajans better.

**Comment by kwhitehall** [comment]
@KillahB please see if the implementation on [cflbajans repo](https://github.com/CFLBajans/cflbajans) addresses this sufficiently. 
EDIT: Open any other related issues against that repo please.

**Comment by KillahB** [comment]
@kwhitehall it does, thanks.
