### ISSUE TITLE
Upcoming Event Page (Other Associations)

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cfbajans-website-legacy#38]
Please create a page where we can highlight upcoming events  / links / contact information to other associations

**Comment by kwhitehall** [comment]
This can be incorporated into the calendar without necessary creating a new page. Thoughts?

**Comment by kwhitehall** [comment]
@KillahB please see if the implementation on [cflbajans repo](https://github.com/CFLBajans/cflbajans) addresses this sufficiently - specifically the Google calendar inclusion of these events. The calendar is found on events.html. 
EDIT: Open any other related issues against that repo please.

**Comment by KillahB** [comment]
@kwhitehall It does. Thanks.
