### ISSUE TITLE
remove the taste of Barbados flyer from main site

### ISSUE THREAD

**Issue by kwhitehall** [CFLBajans/cfbajans-website-legacy#6]

**Comment by kwhitehall** [comment]
Pinging on this and updating the site (issues #7 and #8). The FB page events are updated.

**Comment by kwhitehall** [comment]
Addressed in PR #15 and #16.

**Comment by millserd** [comment]
Sorry for my lateness in getting to this. Looks like you did a good job! Regardless I now have my desktop fully setup to work on further issues.

**Comment by kwhitehall** [comment]
Ack'ed @millserd. Had a few moments this morning, so decided to go for it.
