### ISSUE TITLE
design flyer for bus ride

### ISSUE THREAD

**Issue by kwhitehall** [CFLBajans/cfbajans-website-legacy#7]
For the website.

**Comment by KillahB** [comment]
[Flyer.pptx](https://github.com/CFLBajans/cfbajans-website-legacy/files/924549/Flyer.pptx)

**Comment by KillahB** [comment]
![flyer](https://cloud.githubusercontent.com/assets/26695831/25074314/1082a6d6-22c6-11e7-84d7-103b091eafc6.JPG)

**Comment by KillahB** [comment]
Will do minor edits (blocking out the bus license plates) and changing the Transport Board bus destination to Fort Desoto.

**Comment by KillahB** [comment]
Updated Flyer (PPT) [easily editable] and JPG for your review.
@kwhitehall @cflemming3 @millserd 

[Flyer.pptx](https://github.com/CFLBajans/cfbajans-website-legacy/files/924567/Flyer.pptx)
![flyer](https://cloud.githubusercontent.com/assets/26695831/25074446/c44db852-22c8-11e7-8964-0697a2d9ea65.JPG)

**Comment by kwhitehall** [comment]
jpeg 'Bus' registers weird on my end...

**Comment by KillahB** [comment]
My bad....

![flyer](https://cloud.githubusercontent.com/assets/26695831/25074474/529246dc-22c9-11e7-81b4-fd57e1de807c.JPG)

**Comment by kwhitehall** [comment]
👍 LGTM! Thanks @KillahB!

**Comment by KillahB** [comment]
Final update for today....

[Flyer.pptx](https://github.com/CFLBajans/cfbajans-website-legacy/files/924587/Flyer.pptx)
![flyer](https://cloud.githubusercontent.com/assets/26695831/25074502/1680c80c-22ca-11e7-884c-d49d68644b49.JPG)

**Comment by kwhitehall** [comment]
Thanks again @KillahB! This has been incorporated in PR #15 and #16.

**Comment by cflemming3** [comment]
The flyer looks good. The Bajan buses are misleading lol but a nice touch
none-the-less. The only thing is that some of the words are overlapping on
the pictures.

Christine

**Comment by kwhitehall** [comment]
Thanks for the feedback @cflemming3! I believe the overlapping words are part of the design. @KillahB can weigh in on that tho.

**Comment by millserd** [comment]
The flyer does look good. The overlapping words could be fixed, but is probably not a big deal
